name: nanny_mctea_sitters_flutter

description: Client mobile app for baby sitting business.

version: 1.0.4+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.0.0
  cloud_firestore: ^0.12.9+1
  device_calendar: ^1.0.0+2
  device_info: ^0.4.0+2
  equatable: ^1.1.1
  firebase_auth: ^0.14.0+3
  firebase_core: ^0.4.0+9
  firebase_messaging: ^5.1.6
  firebase_storage: ^3.0.6
  flutter_bloc: ^4.0.0
  flutter_custom_clippers: ^1.0.4
  flutter_money_formatter: ^0.8.3
  get_it: ^3.1.0
  http: ^0.12.0+1 
  package_info: ^0.4.0+6
  image_picker: ^0.6.1+3
  intl: ^0.15.7
  intro_views_flutter: '^2.4.0'
  material_design_icons_flutter: ^3.2.4096
  share: ^0.6.3+5
  table_calendar: ^2.0.1
  timeago: ^2.0.10
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          style: italic
