name: nanny_mctea_sitters_flutter

description: Client mobile app for baby sitting business.

version: 1.0.3+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  algolia: ^0.1.6+1
  cached_network_image: ^1.1.1
  cloud_firestore: ^0.12.9+1
  cupertino_icons: ^0.1.2
  # device_calendar: ^1.0.0+2
  device_info: ^0.4.0+2
  firebase_auth: ^0.14.0+3
  firebase_core: ^0.4.0+9
  firebase_storage: ^3.0.6
  flutter_custom_clippers: ^1.0.4
  flutter_mailer: ^0.4.1+2
  http: ^0.12.0+1 
  package_info: ^0.4.0+6
  image_picker: ^0.6.1+3
  intl: ^0.15.7
  intro_views_flutter: '^2.4.0'
  material_design_icons_flutter: ^3.2.4096
  share: ^0.6.0+1
  table_calendar: ^2.0.1
  timeago: ^2.0.10
  url_launcher: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          # style: italic
